name: Container Build Test
on: 
  pull_request:
    branches:
      - main  
  push:
    paths:
      - builds/Dockerfile
      - builds/podman.Dockerfile

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
            docker buildx build -f builds/python3-slim-bookworm.Dockerfile --platform linux/amd64 --load -t peyeon:buildx .
    
      - name: Run Test Command
        run: |
            docker run --rm peyeon:buildx sh -c "eyeon --help"

  podman-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build Podman Image
        run: |
            podman build -f builds/podman.Dockerfile -t peyeon:podman .
    
      - name: Run Test Command
        run: |
            podman run --rm peyeon:podman sh -c "eyeon --help"
